In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# CUSTOMERS TABLE

# Number of customers
n_customers = 1000


# CUSTOMER ID (starts at 1100)
customer_id = np.arange(11001, 11001 + n_customers)


# Gender
genders = ['Male', 'Female']
gender_data = np.random.choice(genders, n_customers)


# GENDER-SPECIFIC FIRST NAMES
male_first_names = ["John", "Michael", "David", "James", "Daniel", "Robert", "William", "Joseph", "Austin", "Mike", "Adrian",
                   "Frederick", "Matthew", "Noah", "Anthony", "Richard", "Thomas", "Steven", "Donald", "Noah"]
female_first_names = ["Sarah", "Emily", "Laura", "Olivia", "Emma", "Sophia", "Grace", "Hannah", "Jennifer", "Stephanie", "Zoey",
                     "Leah", "Lisa", "Susan", "Ashley", "Emily", "Nancy", "Donna", "Margaret", "Betty"]

# Assign first names based on gender
first_name_data = [
    np.random.choice(male_first_names) if gender == "Male"
    else np.random.choice(female_first_names)
    for gender in gender_data
]


# LAST NAMES (shared across genders)
last_names = ["Smith", "Johnson", "Brown", "Taylor", "Wilson", "Davies", "Evans", "Wilson", "Cooper", "Chybaski", "Wright",
             "Robinson", "Thompson", "Hughes", "Edwards", "Jackson", "Clarke", "Wood", "Jones", "Walker"]
last_name_data = np.random.choice(last_names, n_customers)


# AGE, ratio data
age = np.random.randint(18, 80, n_customers)


# CITY, nominal data
cities = ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow']
city_data = np.random.choice(cities, n_customers)


# LOYALTY TIER, ordinal data
loyalty_levels = ['Bronze', 'Silver', 'Gold', 'Platinum']
loyalty_data = np.random.choice(loyalty_levels, n_customers, p=[0.4, 0.3, 0.2, 0.1])


# REGISTRATION YEAR, interval data
registration_year = np.random.randint(2015, 2024, n_customers)


# Realistic E-mail Addresses
domains = ["gmail.com", "yahoo.com", "yahoo.co.uk", "hotmail.com", "outlook.com", "icloud.com"]

email_data = [
    f"{first.lower()}.{last.lower()}@{np.random.choice(domains)}"
    for first, last in zip(first_name_data, last_name_data)
]


# Organizing data frame
df_customers = pd.DataFrame({
    'customer_id': customer_id,
    'first_name': first_name_data,   # Nominal
    'last_name': last_name_data,
    'gender': gender_data,
    'age': age,
    'loyalty_tier': loyalty_data,
    'city': city_data,
    'registration_year': registration_year,
    'email': email_data
})


df_customers.head()

,customer_id,first_name,last_name,gender,age,loyalty_tier,city,registration_year,email
0,11001,Austin,Chybaski,Male,23,Bronze,Birmingham,2019,austin.chybaski@gmail.com
1,11002,Noah,Clarke,Male,72,Bronze,Manchester,2021,noah.clarke@gmail.com
2,11003,Donna,Thompson,Female,30,Gold,Glasgow,2017,donna.thompson@yahoo.com
3,11004,Stephanie,Robinson,Female,57,Bronze,Birmingham,2015,stephanie.robinson@yahoo.co.uk
4,11005,David,Chybaski,Male,33,Silver,Manchester,2017,david.chybaski@hotmail.com

In [3]:
# PRODUCTS TABLE

n_products = 250

# Realistic product catalogue & brand, Nominal data (each product appears once)

catalogue = {
    "Dairy": {
        "Tesco": ["Milk 2L", "Cheddar Cheese 400g", "Greek Yogurt 500g", "Butter 250g"],
        "Arla": ["Organic Milk 2L", "Skyr Yogurt 450g"]
    },
    "Bakery": {
        "Hovis": ["Wholemeal Bread", "Seeded Loaf"],
        "Tesco": ["Croissants 4 Pack", "Bagels 5 Pack", "Chocolate Muffins"]
    },
    "Beverages": {
        "Coca-Cola": ["Coca-Cola 2L"],
        "Tropicana": ["Orange Juice 1L"],
        "Evian": ["Mineral Water 6 Pack"],
        "Twinings": ["Green Tea"]
    },
    "Snacks": {
        "Walkers": ["Walkers Crisps"],
        "McVitie's": ["Digestive Biscuits"],
        "Mars": ["Snickers Bar"],
        "Pringles": ["Pringles Original"]
    },
    "Produce": {
        "Tesco": ["Bananas 1kg", "Apples 6 Pack", "Carrots 1kg", "Broccoli"]
    },
    "Meat": {
        "Tesco": ["Chicken Breast 1kg", "Beef Mince 500g", "Pork Sausages", "Lamb Chops"]
    },
    "Frozen": {
        "Tesco": ["Frozen Pizza", "Ice Cream 1L", "Fish Fingers", "Frozen Peas"]
    }
}

product_rows = []

for category, brands in catalogue.items():
    for brand, products in brands.items():
        for product in products:
            product_rows.append({
                "product_name": product,  # Nominal data
                "category": category,     # Nominal data
                "brand": brand            # Nominal data
            })

df_products = pd.DataFrame(product_rows)


df_products = df_products.sample(n=n_products, replace=True).reset_index(drop=True)

# product_id, Ratio data, Primary Key
df_products["product_id"] = range(5001, 5001 + n_products)

# Price ranges by category, Ratio data
price_ranges = {
    "Dairy": (0.80, 4.50),
    "Bakery": (1.00, 3.50),
    "Beverages": (0.50, 6.00),
    "Snacks": (0.60, 3.00),
    "Produce": (0.50, 2.50),
    "Meat": (3.00, 12.00),
    "Frozen": (1.00, 6.00)
}

# Price_GBP, ratio data
df_products["price_GBP"] = df_products.apply(
    lambda row: round(
        np.random.uniform(*price_ranges[row["category"]]), 2
    ),
    axis=1
)

# stock_quantity, Ratio data
df_products["stock_quantity"] = np.random.randint(20, 200, n_products)

# rating_score, Interval data
df_products["rating_score"] = np.round(np.random.uniform(3.0, 5.0, n_products), 1)


# Introduce missing values in stock_quantity (simulate real-world data issues)
n_missing = 20
random_indices = np.random.choice(df_products.index, n_missing, replace=False)
df_products.loc[random_indices, 'stock_quantity'] = np.nan


df_products.head()

,product_name,category,brand,product_id,price_GBP,stock_quantity,rating_score
0,Beef Mince 500g,Meat,Tesco,5001,8.69,140.0,3.3
1,Pringles Original,Snacks,Pringles,5002,2.47,170.0,4.6
2,Milk 2L,Dairy,Tesco,5003,4.39,109.0,3.1
3,Frozen Peas,Frozen,Tesco,5004,4.84,144.0,4.0
4,Ice Cream 1L,Frozen,Tesco,5005,5.28,44.0,3.2

In [4]:
# TRANSACTIONS TABLE

n_transactions = 4000

# Transaction ID (primary key), Ratio data
transaction_id = np.arange(91001, 91001 + n_transactions)

# Foreign key to customers table, Ratio data
customer_fk = np.random.choice(df_customers["customer_id"], n_transactions)

# Interval data, more recent years have more transactions
transaction_year = np.random.choice(
    [2020, 2021, 2022, 2023, 2024],
    n_transactions,
    p = [0.05, 0.10, 0.20, 0.30, 0.35]
)

# Generate full transaction dates (day + month + year)
transaction_date = []
for year in transaction_year:
    start = pd.Timestamp(f"{year}-01-01")
    end = pd.Timestamp(f"{year}-12-31")
    random_day = start + pd.to_timedelta(
        np.random.randint(0, (end - start).days + 1), unit="D"
    )
    transaction_date.append(random_day)


transaction_date = pd.to_datetime(transaction_date)
transaction_date = transaction_date.strftime("%Y-%m-%d")

# Nominal data
payment_methods = ["Cash","Debit Card","Credit Card","Apple Pay","Google Pay"]
payment_data = np.random.choice(payment_methods,
                                n_transactions,
                               p = [0.05, 0.10, 0.20, 0.30, 0.35])


branches = ["London Central","Manchester Arndale",
            "Birmingham Bullring","Leeds Trinity","Glasgow Centre"]

# larger cities get more traffic
branch_data = np.random.choice(
    branches,
    n_transactions,
    p=[0.30, 0.25, 0.20, 0.15, 0.10]
)

# RATIO DATA, realistic store basket range
basket_ranges = {
    "London Central": (6, 40),
    "Manchester Arndale": (8, 60),
    "Birmingham Bullring": (10, 70),
    "Leeds Trinity": (10, 80),
    "Glasgow Centre": (8, 55)
}


# Ordinal data, customer's satisfaction
satisfaction_level = np.random.choice([1,2,3,4,5], n_transactions,
                                      p=[0.05,0.1,0.2,0.35,0.3])

df_transactions = pd.DataFrame({
    'transaction_id': transaction_id,
    'customer_id': customer_fk,
    'transaction_date': transaction_date,
    'payment_method': payment_data,
    'satisfaction_level': satisfaction_level,
    'store_branch': branch_data
})


df_transactions.head()

,transaction_id,customer_id,transaction_date,payment_method,satisfaction_level,store_branch
0,91001,11618,2024-01-29,Credit Card,5,Manchester Arndale
1,91002,11453,2022-10-18,Debit Card,4,London Central
2,91003,11645,2023-03-23,Google Pay,4,Birmingham Bullring
3,91004,11690,2024-02-24,Google Pay,5,Leeds Trinity
4,91005,11451,2024-05-20,Google Pay,5,London Central

In [5]:
# TRANSACTION ITEMS TABLE (Compound Key)

transaction_items_list = []

for trans_id in df_transactions["transaction_id"]:

    n_items = np.random.randint(1, 9)  # 1–8 products per basket
    selected_products = np.random.choice(df_products["product_id"], n_items, replace=False)

    for prod_id in selected_products:

        quantity = np.random.randint(1, 10)
        unit_price = df_products.loc[df_products["product_id"] == prod_id, "price_GBP"].values[0]

        transaction_items_list.append({
            "transaction_id": trans_id,
            "product_id": prod_id,
            "quantity": quantity,
            "unit_price_GBP": unit_price
        })

df_transaction_items = pd.DataFrame(transaction_items_list)

# Compound Primary Key
df_transaction_items.head()

   transaction_id  product_id  quantity  unit_price_GBP
0           91001        5195         9            1.95
1           91001        5226         7            1.53
2           91001        5167         1            1.14
3           91001        5135         1           11.85
4           91001        5045         2            1.52

In [6]:
# Calculate total_amount_GBP, for the transactions table for it to be realistic

# 1. Drop any old total columns created by previous attempts
cols_to_drop = [c for c in df_transactions.columns if "total_amount_GBP" in c]
df_transactions = df_transactions.drop(columns=cols_to_drop, errors="ignore")

df_transaction_items["line_total_GBP"] = (
    df_transaction_items["quantity"] * df_transaction_items["unit_price_GBP"]
).round(2)

transaction_totals = (
    df_transaction_items
    .groupby("transaction_id")["line_total_GBP"]
    .sum()
    .round(2)
    .reset_index()
    .rename(columns={"line_total_GBP": "total_amount_GBP"})
)

df_transactions = df_transactions.merge(transaction_totals, on="transaction_id", how="left")

df_transactions.head()

,transaction_id,customer_id,transaction_date,payment_method,satisfaction_level,store_branch,total_amount_GBP
0,91001,11618,2024-01-29,Credit Card,5,Manchester Arndale,104.00
1,91002,11453,2022-10-18,Debit Card,4,London Central,103.73
2,91003,11645,2023-03-23,Google Pay,4,Birmingham Bullring,31.90
3,91004,11690,2024-02-24,Google Pay,5,Leeds Trinity,23.21
4,91005,11451,2024-05-20,Google Pay,5,London Central,78.73

In [7]:
# Print the number of rows and columns of the tables generated.
print("customers:", df_customers.shape)
print("products:", df_products.shape)
print("transactions:", df_transactions.shape)
print("transaction_items:", df_transaction_items.shape)

customers: (1000, 9)
products: (250, 7)
transactions: (4000, 7)
transaction_items: (18175, 5)

In [8]:
# Exporting / Saving tables generated for SQLite import

df_customers.to_csv("Customers.csv")
df_products.to_csv("Products.csv")
df_transactions.to_csv("Transactions.csv")
df_transaction_items.to_csv("Transaction_Items.csv")

print("All CSV files successfully generated.")

All CSV files successfully generated.

In [9]:
from google.colab import files
import sqlite3


# CREATE SQLITE DATABASE

conn = sqlite3.connect("retail_database.db")
cursor = conn.cursor()

# Enable foreign keys
cursor.execute("PRAGMA foreign_keys = ON;")

# DROP TABLES IF THEY EXIST (CLEAN START)

cursor.executescript("""
DROP TABLE IF EXISTS Transaction_Items;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Customers;
""")


# CREATE TABLES WITH CONSTRAINTS

cursor.executescript("""

CREATE TABLE Customers (
    customer_id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    gender TEXT NOT NULL CHECK (gender IN ('Male','Female')),
    age INTEGER NOT NULL CHECK (age BETWEEN 18 AND 100),
    loyalty_tier TEXT NOT NULL CHECK (loyalty_tier IN ('Bronze','Silver','Gold','Platinum')),
    city TEXT NOT NULL,
    registration_year INTEGER NOT NULL CHECK (registration_year BETWEEN 2015 AND 2024),
    email TEXT NOT NULL
);

CREATE TABLE Products (
    product_id INTEGER PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL,
    brand TEXT NOT NULL,
    price_GBP REAL NOT NULL CHECK (price_GBP > 0),
    stock_quantity INTEGER CHECK (stock_quantity >= 0),
    rating_score REAL CHECK (rating_score BETWEEN 1 AND 5)
);

CREATE TABLE Transactions (
    transaction_id INTEGER PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    transaction_date DATE NOT NULL CHECK (transaction_date BETWEEN '2020-01-01' AND '2025-12-31'),
    payment_method TEXT NOT NULL CHECK (
        payment_method IN ('Cash','Debit Card','Credit Card','Apple Pay','Google Pay')
    ),
    satisfaction_level INTEGER CHECK (satisfaction_level BETWEEN 1 AND 5),
    store_branch TEXT NOT NULL,
    total_amount_GBP REAL CHECK (total_amount_GBP >= 0),

    FOREIGN KEY (customer_id)
        REFERENCES Customers(customer_id)
        ON DELETE CASCADE
);

CREATE TABLE Transaction_Items (
    transaction_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_GBP REAL NOT NULL CHECK (unit_price_GBP > 0),
    line_total_GBP REAL NOT NULL CHECK (line_total_GBP >= 0),

    PRIMARY KEY (transaction_id, product_id),

    FOREIGN KEY (transaction_id)
        REFERENCES Transactions(transaction_id)
        ON DELETE CASCADE,

    FOREIGN KEY (product_id)
        REFERENCES Products(product_id)
);

""")

conn.commit()


# INSERT DATA FROM DATAFRAMES

df_customers.to_sql("Customers", conn, if_exists="append", index=False)
df_products.to_sql("Products", conn, if_exists="append", index=False)
df_transactions.to_sql("Transactions", conn, if_exists="append", index=False)
df_transaction_items.to_sql("Transaction_Items", conn, if_exists="append", index=False)


conn.commit()

In [10]:
# VERIFY DATA

for table in ["Customers","Products","Transactions","Transaction_Items"]:
    count = cursor.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    print(f"{table}: {count} rows")

conn.close()

print("Database finished")

Customers: 1000 rows
Products: 250 rows
Transactions: 4000 rows
Transaction_Items: 18175 rows
Database finished